server:
  port: 8088

spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mybatisplus_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    props:
      sql:
        show: true
    sharding:
      # 默认数据源
      default-data-source-name: ds0
      tables:
        user:
          actual-data-nodes: ds0.user_$->{2020..2021}_$->{01..12}
          table-strategy:
            standard:
              sharding-column: create_time
              preciseAlgorithmClassName: com.fast.mybatisplus.architechturespringmybatisplus.config.OrderPreciseShardingTableAlgorithm
              rangeAlgorithmClassName: com.fast.mybatisplus.architechturespringmybatisplus.config.OrderRangeShardingTableAlgorithm
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
      # 全局的主键生成策略
      id-type: auto
