server:
  port: 8087

grpc:
  client:
    local-grpc-server:
      address: 'static://192.168.3.44:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: TLS
    GLOBAL:
      security:
        client-auth-enabled: true
        certificateChain: classpath:cert/server.crt
        privateKey: classpath:cert/server.key
        authority-override: localhost
